# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FTTestCocoapods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'FTZoomTransition', '~> 0.0.5'
pod 'FTPopOverMenu'
pod 'FTImageViewer'
pod 'FTIndicator'
pod 'Alamofire'
  # Pods for FTTestCocoapods

end
